### ISSUE TITLE
Kept putting a \r on end of my items

### ISSUE THREAD

**Issue by rcojoe** [varunsridharan/wc-bulk-product-delete#1]
in the function delete_product_id
Around line 51, I put added
       foreach($ids as $id){
			$id = str_replace("\r","",$id);
			if ($id == "") break;
                       $delete = $delete_function($id);

and that solved my issue.

**Comment by varunsridharan** [comment]
@rcojoe thanks for the fix. sure i will update the plugin

**Comment by rcojoe** [comment]
Fixed with this merge. https://github.com/varunsridharan/WooCommerce-Bulk-Product-Delete/pull/2
